services:
  task-api:
    build:
      context: ./task-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://task-management-db.cknw6is8qybw.us-east-1.rds.amazonaws.com:3306/task_management
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=MySecurePass123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - task-network

  task-ui:
    build:
      context: ./task-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - task-api
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
