version: '3.8'
services:
  task-api:
    build:
      context: ./task-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - task-network

  task-ui:
    build:
      context: ./task-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - task-api
    networks:
      - task-network

networks:
  task-network:
    driver: bridge